### ISSUE TITLE
Performance boost

### ISSUE THREAD

**Issue by andywer** [andywer/use-inline-memo#1]
Turns out, that the stack trace creation is indeed relatively expensive (~0.2ms in Chrome on my MacBook Pro). It happens on every call to `memo()`.

Find the pull request for the intended change here: #3

Original PR: #2
See below.

---

## Solution

Instead of matching call site to memoized value by stack trace creation, we should do it like this:

- Create a counter (just a number var) for every call to `useInlineMemo()`
- On call to `memo()`:
  - Replace the call site as a key to a memoized value with the current counter value
  - Increment counter

This way we also map every call to `memo()` to a memoized value, but based upon the order of the `memo()` calls, not based on the call site location.

## Limitations

Conditionally executed code blocks using `memo()` will cause memoized values of later calls to be invalidated if the code block was run before and then is not anymore or was not run before and is now.

#### Example

```js
function MyComponent(props) {
  const memo = useInlineMemo()

  if (props.disabled) {
    return <div style={memo({ opacity: 0.5 }, [])}>Disabled</div>
  }

  return (
    <button onClick={memo(() => props.onStateChange(true))}>Do stuff</button>
  )
}
```

If `props.disabled` switches to `true`, it will invalidate the memoized value of the onClick handler, as the style memo now occupies the counter value that the onClick memo used to have.

Similarly, if `props.disabled` becomes `false`, it will invalidate the memoized value of style/onClick once more.

#### Impact of that limitation

**Might not be an issue in most real-world use cases as state changes that cause conditional code blocks to change behavior will frequently cause major DOM updates for this component. Losing memoized values could be acceptable, as a lot of expensive reconciliation has to be done anyway.**

Best case scenario: The loss of memoized values as a result of conditional code and state changes does not have any performance impact at all as oftentimes the lost values refer to elements that are about to be unmounted.

**Comment by andywer** [comment]
This solution does not work, though. Simple counter example as provided by @just-boris:

```jsx
function Demo() {
   const [count, setCount] = React.useState(0)
   const memo = useInlineMemo()

   if (isDecrementing) {
      return <button onClick={memo(() => setCount(count - 1), [count])}>Decrement</button>
   } else {
      return <button onClick={memo(() => setCount(count + 1), [count])}>Increment</button>
   }
}
```

There are, however, two more solutions that we can consider.

## Alternative 1 - Babel plugin / TypeScript transform

We create a Babel plugin and a TypeScript transform to rewrite every `memo()` call, so it explicitly adds a caller identifier:

```jsx
// before
const memo = useInlineMemo()
return <button onClick={memo(() => doStuff(true), [])}>Click me</button>
```
```jsx
// after
const memo = useInlineMemo()
return <button onClick={memo(() => doStuff(true), [], 1)}>Click me</button>
```

As suggested by @Anber.

## Alternative 2

Less elegant, but easier to implement: Instantiate multiple memo functions up-front, as outlined in this [comment](https://github.com/andywer/use-inline-memo/pull/2#issuecomment-522345073):

```jsx
function Demo() {
   const [count, setCount] = React.useState(0)
   const [memoInc, memoDec] = useInlineMemos()

   if (isDecrementing) {
      return <button onClick={memoInc(() => setCount(count - 1), [count])}>Decrement</button>
   } else {
      return <button onClick={memoDec(() => setCount(count + 1), [count])}>Increment</button>
   }
}
```

**Comment by andywer** [comment]
Slightly different approach to alternative 2:

```jsx
function Demo() {
  const [count, setCount] = React.useState(0)
  // if you target ES2015+ browsers
  const memo = useInlineMemo()
  // or if you need to support IE
  const memo = useInlineMemo("increment", "decrement")

  if (isDecrementing) {
    return <button onClick={memo.increment(() => setCount(count - 1), [count])}>Decrement</button>
  } else {
    return <button onClick={memo.decrement(() => setCount(count + 1), [count])}>Increment</button>
  }
}
```

In this scenario the `X` in `memo.X` identifies the memo call. In ES2015+ runtimes we can use a `Proxy`, so you don't have to list the properties on `memo` in advance. If you need to support old browsers, you need to list them explicitly.

Motivation: Might lead to friendlier looking code without the need for Babel plugins and TypeScript transforms.

@Anber @just-boris What do you think?

**Comment by Anber** [comment]
It looks interesting!
Btw, maybe it should show a warning if `memo.X` is called more than once? Because it's probably a copy-paste error and can cause problem if one of the call will be used with condition.

**Comment by andywer** [comment]
Yeah, that warning makes a lot of sense and it's easy to implement 👍
